# Generated by Django 2.2.5 on 2020-01-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200116_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='coutry',
            new_name='country',
        ),
    ]
